version: 2.1

orbs:
  node: circleci/node@4.0.0

defaults: &defaults
  docker:
    - image: cimg/base:stable-20.04
  working_directory: ~/repo

commands:
  install_cci_cli:
    description: Install CircleCLI
    steps:
      - run:
          name: Install CCI CLI
          command: |
            sudo curl -fLSs https://circle.ci/cli | sudo bash
          
jobs:
  pack-orb:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: See files after checkout
          command: |
            ls -la
      - install_cci_cli
      - run:
          name: Pack the Orb
          command: |
            mkdir packed
            /usr/local/bin/circleci orb pack src >> packed/orb.yml
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  btd:
    jobs:
      - pack-orb