version: 2.1

orbs:
  node: circleci/node@4.0.0

defaults: &defaults
  docker:
    - image: cimg/base:stable-20.04
  working_directory: ~/repo

commands:
  install_cli:
    description: Install CircleCLI
    steps:
      - run:
          name: Install CircleCLI
          command: |
            sudo curl -fLSs https://circle.ci/cli | sudo bash
          
jobs:
  build-orb:
    <<: *defaults
    steps:
      - checkout
      - install_cli
      - run:
          name: Pack the Orb using CircleCLI
          command: |
            mkdir build
            /usr/local/bin/circleci orb pack src >> build/orb.yml
      - persist_to_workspace:
          root: .
          paths:
            - .

  dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - install_cli
      - run:
          name: Deploy dev version of ShiftLeft
          command: |
            dev_orb_tag="chkp-mibraun/shiftleft@dev:${CIRCLE_BRANCH}"
            echo "dev_orb_ref: ${dev_orb_ref}"
            /usr/local/bin/circleci orb publish build/orb.yml $dev_orb_tag --token $CIRCLECI_TOKEN
      - store_artifacts:
          path: build/orb.yml

workflows:
  btd:
    jobs:
      - build-orb
      - dev:
          requires:
            - build-orb